version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  data-builder-db:
    container_name: data-builder-db
    image: "postgres:latest"
    restart: on-failure
    # <Port exposed> : <Port running inside container>
    ports:
      - "5632:5432"
    environment:
      POSTGRES_DB: double-dice-data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg123
    # Opens port 5632 on the container
    expose:
      - 5632
  #    networks:
  #      - defaultdata

  data-builder:
    container_name: data-builder
    depends_on:
      - data-builder-db
    build:
      context: .
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1700M
        reservations:
          cpus: '0.15'
          memory: 200M
    restart: on-failure
    ports:
      - "8780:8780"
    expose:
      - 8780
#    networks:
#      - outside
#      - default
#networks:
#  outside:
##    external: true