spring:
  jackson:
    serialization:
      indent-output: true
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        query:
          plan_cache_max_size: 512
          plan_parameter_metadata_max_size: 32
          in_clause_parameter_padding: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/double-dice-data?createDatabaseIfNotExist=true
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  security:
    oauth2:
      client:
        registration:
          vk-app:
            provider: vk
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            serviceSecret: ${SERVICE_SECRET:}
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            group_ids: "72574230"
            defaultUserName: ${DEFAULT_USER_NAME}
            defaultUserPass: ${DEFAULT_USER_PASS}
            defaultAdminName: ${DEFAULT_ADMIN_NAME}
            defaultAdminPass: ${DEFAULT_ADMIN_PASS}
            scope:
              - manage
            redirect-uri: "http://localhost/vk/code"
        provider:
          vk:
            authorization-uri: https://oauth.vk.com/authorize
            token-uri: https://oauth.vk.com/access_token
            user-info-uri: https://api.vk.com/method/users.get
  main:
    allow-circular-references: true
server:
  port: 80


